fix(messageController.ts) : this..validationError = new ValidationError(this);
 ^

ValidationError: Message validation failed: content: Cast to ObjectId failed for value '' (type string) at path 'content' because of 'BSONError'